### ISSUE TITLE
Update to Macros 1.1

### ISSUE THREAD

**Issue by dtolnay** [JelteF/derive_more#1]
Check out [`treeflection_derive`](https://github.com/rukai/treeflection/blob/f9c6c9361bfd74e8e255c70a0623f0a19c53971c/treeflection_derive/src/lib.rs) for an example of the new system, the [RFC](https://github.com/rust-lang/rfcs/pull/1681) for the motivation around why code written against Macros 1.1 will be more stable than using plugin_registrar, and the [tracking issue](https://github.com/rust-lang/rust/issues/35900) to keep up with progress on stabilizing Macros 1.1.

**Comment by JelteF** [comment]
I'm gonna be looking in to this now.

**Comment by JelteF** [comment]
This seems to be way more work than I hoped my progress can be seen on the `macros-1.1` branch.

**Comment by JelteF** [comment]
It's taking some time, but I'm making serious progress. The only thing that still needs to be converted are the `mul_like` derives :smile:.

**Comment by JelteF** [comment]
I just released version 0.4.0 which passes all previously created tests with Macros 1.1 :), The lib now works on the beta channel! 

Thanks for the great quote and syn libraries. The new code is much nicer and more readable.
