### ISSUE TITLE
Don't derive From by default for variants without fields

### ISSUE THREAD

**Issue by JelteF** [JelteF/derive_more#106]
There's not really a reason to derive from for `()` for variants without fields. It's somewhat unexpected and results in the problems described here in #105. Let's remove this in the next breaking release, probably 1.0.

**Comment by Robbepop** [comment]
Could you also please make a warning if a crate has some spurious `#[from(ignores)]` that it would no longer need with version 1.0. I currently am having many of those `#[from(ignore])` annotations in my crates and it would be a blessing to have some indicators by the macro itself if they are no longer useful.
