### ISSUE TITLE
Other macro attributes not passed through to generated code?

### ISSUE THREAD

**Issue by Sushisource** [JelteF/derive_more#109]
Love the library, thanks for your work. Wanted to point out a small bug:

I have a struct like:
```rust
#[allow(clippy::too_many_arguments)]
#[derive(Constructor, Clone)]
pub struct SomeStruct {
    pub field1: String,
 ...
    pub field10: String
}
```

The `allow` attribute doesn't seem to get passed through to the generated constructor. I'd expect this to work generally for lints.

Thanks!

**Comment by JelteF** [comment]
This shouldn't be an issue anymore in practice, since we now add `#[automatically_derived]` to all derives.
