### ISSUE TITLE
#[derive(From)] for generics

### ISSUE THREAD

**Issue by dingfengquek** [JelteF/derive_more#12]
Awesome library!
But
```rs
struct Oldtype<T> {
    x: T
}

#[derive(From)]
struct Newtype<'a>(Oldtype<'a>);
```
doesn't work because

```rs
fn newtype_from(input_type: &Ident, original_type: &Ty) -> Tokens {
    quote!{
        impl ::std::convert::From<#original_type> for #input_type {
            fn from(original: #original_type) -> #input_type {
                #input_type(original)
            }
        }
    }
}
```
doesn't do `impl<...>`

**Comment by JelteF** [comment]
Good find, this should be easy to fix by just adding the `<...>` to the`impl`.

**Comment by JelteF** [comment]
This is likely also the case for all other derivations provided by this lib.

**Comment by JelteF** [comment]
I fixed it for `From` for structs on the version on git can you confirm that it fixes the issue for you? I'll fix the `From` for enums at the same time that I fix #10. 

The other traits almost certainly have this problem as well. I'll fix them eventually as well, but pull requests are of course appreciated. It shouldn't be too hard to fix them when using the changes to `From` as an example.

**Comment by dingfengquek** [comment]
Thanks, it works :)

No idea about the other derives because I've never used them before.

**Comment by JelteF** [comment]
This is fixed now for enums as well.
