### ISSUE TITLE
Try out Watt for faster compilation

### ISSUE THREAD

**Issue by JelteF** [JelteF/derive_more#120]
https://crates.io/crates/watt

**Comment by jhpratt** [comment]
I don't know if there's been any significant updates that haven't been released yet, but when I asked David before, he said it's definitely not production ready.

**Comment by matklad** [comment]
Another way to improve compile times is to get rid of `extra-traits` feature of `syn`, as that inflates compile times quite a bit.

**Comment by JelteF** [comment]
@matklad good point. I just released 0.99.7, where this `syn` feature is only enabled for the derives that need it (if you use the derive_more features). Changing the derives to not require it would be significant work.

**Comment by JelteF** [comment]
With all the drama around serde doing this, i'm going to close this.

**Comment by tyranron** [comment]
@JelteF I've also used it for years in some my projects, and the experience wasn't so smooth around it. I had some breakages between minor version where old wasm binary was failing to run on newer watt runtimes.
