### ISSUE TITLE
Derive fails silently when missing `fmt =`

### ISSUE THREAD

**Issue by branpk** [JelteF/derive_more#127]
When `fmt =` is left out from the derive, no error is thrown and the default derive behavior is used:
```rust
use derive_more::Display;

#[derive(Display)]
#[display("custom {}", x)]
struct A {
    x: i32,
}

fn main() {
    println!("{}", A { x: 1 }); // prints "1"
}
```
I feel this is an easy mistake to make, so I would expect the macro to throw an error in this case.

derive_more 0.99.5, rustc 1.45.0-nightly

**Comment by JelteF** [comment]
Yeah that's not great indeed. A PR for this is welcome.
