### ISSUE TITLE
Deriving DerefMut should automatically also derive Deref since it depends on it

### ISSUE THREAD

**Issue by Boscop** [JelteF/derive_more#128]
Deriving DerefMut should automatically also derive Deref since it depends on it:
```rust
pub trait DerefMut: Deref {
```

**Comment by JelteF** [comment]
I've thought about this before, but no. This is also not done by the stdlib for traits like `Eq` and `Ord`, which depend on `PartialEq` and `PartialOrd`. https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a678afa2806a30f2718fc6c49202b5c9
