### ISSUE TITLE
Constructor generated new should be marked const

### ISSUE THREAD

**Issue by KarelPeeters** [JelteF/derive_more#131]
For example, given this struct:
```rust
#[derive(Constructor)]
struct Foo { x: f32, y: f32 }
```
The generated code should be:
```rust
impl Foo {
    const fn new(x: f32, y: f32) -> Self {
        Self { x, y }
    }
}
```

As far as I know this should be fine to do on the current stable. It's an easy change, would a PR adding this be accepted?

**Comment by JelteF** [comment]
A pull request would be accepted for this assuming it doesn't break Rust 1.36.0 (which is the currently lowest supported Rust). To do so you might have to check the version with `rustc_version` in the `build.rs` script.

**Comment by flaghacker** [comment]
Unfortunately `const fn` is not quite as stable as I thought, for example trait bounds aren't yet supported in stable (https://github.com/rust-lang/rfcs/pull/2632). I think this issue will have to wait until `const fn` is more mature.

**Comment by krojew** [comment]
Any plans for this? Having const constructors would be a nice feature.

**Comment by appetrosyan** [comment]
One option for how it could be rendered is if we add `#[CosntConstructor]` to the derive macros. Then if the `const`-ness is not supported you have alternatives. No need for complex logic, just a conscious choice.
