### ISSUE TITLE
#[from(forward)] doesn't declare enough generics in the impl

### ISSUE THREAD

**Issue by tylerhawkes** [JelteF/derive_more#133]
I have a protobuf generated from prost that looks like
```
pub struct Reply {
  error: Option<Error>,
  reply: Option<Reply>,
}
```
If I add `#[from(forward)]` to it then the generated code is 
```
        impl<__FromT1> ::core::convert::From<(__FromT0, __FromT1)> for Reply
        where
            ::core::option::Option<Reply>: ::core::convert::From<__FromT1>,
        {
            #[allow(unused_variables)]
            #[inline]
            fn from(original: (__FromT0, __FromT1)) -> Reply {
                Reply {
                    error: <::core::option::Option<Error> as ::core::convert::From<__FromT0>>::from(
                        original.0,
                    ),
                    reply:
                        <::core::option::Option<Reply> as ::core::convert::From<
                            __FromT1,
                        >>::from(original.1),
                }
            }
        }
```
which is almost correct but the impl doesn't declare `__FromT0` as a generic so it fails to compile. The where clause also leaves out `__FromT0` so it doesn't constrain the type properly. 

Probably separate from this issue is the fact that these should probably use `Into` instead of `From` since in the past it could be more widely implemented. If I get some time I'll see about making the fix and a pull request.

**Comment by JelteF** [comment]
This is now fixed in 0.99.9 (it was a small bug in the code). Keep in mind `#[from(forward)]` does not work for structs with generic types that have a single field, because of this issue: https://stackoverflow.com/questions/37347311/how-is-there-a-conflicting-implementation-of-from-when-using-a-generic-type

Also, could you expand on the `Into` vs `From` thing you mention? The docs on `Into` say that you should prefer implementig `From`, so that's what this library does: 
> It is important to understand that `Into` does not provide a `From` implementation (as `From` does with `Into`). Therefore, you should always try to implement `From` and then fall back to `Into` if `From` can't be implemented.

source: https://doc.rust-lang.org/std/convert/trait.Into.html

**Comment by tylerhawkes** [comment]
As the docs say you should fall back to `Into` if `From` can't be implemented which generally used to be the case. You should still implement `From`, but because of this in the type bounds the type should require that `Into` is implemented since it will capture more types that can be turned into the type you want.

**Comment by JelteF** [comment]
Hmm, I understand what you mean. I feel like it has some downside too
though, so it should probably have a flag. Could you make a separate issue
for this with a concrete example where the current behaviour is not what
you want? And the code that you would want derived instead.

**Comment by tylerhawkes** [comment]
Yes. It may take a few days but I'll open an issue with the information.
