### ISSUE TITLE
Conflict implementation of trait

### ISSUE THREAD

**Issue by losintikfos** [JelteF/derive_more#147]
Does anyone know why I am getting below error:

> conflicting implementations of trait `std::convert::From<std::string::String>` for MyError

```
use derive_more::{Display, From};

#[derive(Debug, Display, From)]
pub enum MyError {
    #[display(fmt = "System Error")]
    SystemError,

    #[display(fmt = "System Error: {}", _0)]
    SystemErrorCustom(String),

    #[display(fmt = "DB Error")]
    DbError,

    #[display(fmt = "Database Error: {}", _0)]
    DbErrorCustom(String),
}
```

Cargo.toml: `derive_more = "0.99.11"`

**Comment by Overdrivr** [comment]
@losintikfos Facing the same error, probably a misuse of the library, how did you solve it ?

**Comment by horacimacias** [comment]
not sure what @losintikfos did but I believe part of the problem is having two enum variants that embed a String; you'll probably have to `#[from(ignore)]` one of them at least.
