### ISSUE TITLE
Roadmap and Contributing

### ISSUE THREAD

**Issue by ronlobo** [JelteF/derive_more#148]
Hey folks,

Thanks for putting together this crate, it is very useful for implementing value objects.

Is there a roadmap for the project?

Are there specific contribution guidelines?

Thanks!

**Comment by JelteF** [comment]
Roadmap is getting 1.0 out the door, and then whatever contributors want to help work on.

Contributing guidelines have been available for a while now: https://github.com/JelteF/derive_more/blob/master/CONTRIBUTING.md
