### ISSUE TITLE
#[derive(IsVariant)] clashes with #![deny(missing_docs)]

### ISSUE THREAD

**Issue by snowpoke** [JelteF/derive_more#159]
Trying to run the following code

```rust
#![deny(missing_docs)]
//! Documented crate.
use derive_more::IsVariant;

/// Documented enum.
#[derive(IsVariant)]
pub enum Documented{
    /// Documented variant
    Foo,
    /// Documented variant
    Bar,
}
```

will result in two errors, 

> missing documentation for an associated function rustc(missing_docs) [6,10]
> missing documentation for an associated function rustc(missing_docs) [6,10]

I assume that's a bug on the side of derive_more? At the moment my only workaround is to #![allow(missing_docs)] the entire module, which is a bit unfortunate.

(This is my first filed issue on GitHub btw, I hope I did this right 😳 )

**Comment by Technohacker** [comment]
Can confirm the same with the `Unwrap` derive as well

**Comment by JelteF** [comment]
A pull request to fix this is definitely welcome.
