### ISSUE TITLE
Support thiserror like formatting for Display derive

### ISSUE THREAD

**Issue by Luro02** [JelteF/derive_more#162]
I would love to be able to do this:

```rust
#[derive(Display)]
#[display("{major}.{minor}.{patch}")]
pub struct Version {
    major: usize,
    minor: usize,
    patch: usize,
}
```

instead of

```rust
#[derive(Display)]
#[display(fmt = "{}.{}.{}", major, minor, patch)]
pub struct Version {
    major: usize,
    minor: usize,
    patch: usize,
}
```

[`thiserror`](https://docs.rs/thiserror) allows the first example, so it should be possible to be implemented.

**Comment by JelteF** [comment]
I would definitly like to have this feature, feel free to open a PR implementing it.

**Comment by tyranron** [comment]
@JelteF I believe this has been fully covered by #182
