### ISSUE TITLE
Was `#[mul(forward)]` removed?

### ISSUE THREAD

**Issue by U007D** [JelteF/derive_more#165]
I'm exploring the limits of generic arithmetic and am seeing some odd behavior requiring `Mul<NewType> for InnerType` to be implemented when I `#[derive(Mul)]` on `NewType`.

In my case it makes no sense to support `InnerType * NewType`, so I wonder if `#[mul(forward)]` would give me a simpler impl.

Problem is `#[mul(forward)]` doesn't compile. 
```rust
error: cannot find attribute `mul` in this scope
  --> src/primitives/vec3.rs:17:3
   |
17 | #[mul(forward)]
   |   ^^^
```
I see no examples or tests for it either.  Is `#[mul(forward)]` actually a thing?
I'm on `derive_more v0.99.14`, `rustc 1.55.0-nightly 2021-06-14`.

**Comment by JelteF** [comment]
It's definitly a thing. Is it possible that you forgot to add `#[derive(Mul)]`. If not, can you share the full struct declaration?

**Comment by U007D** [comment]
Could have sworn I tried that; it wasn't 100% clear from the docs, but I tried many other variations (`use derive_more::mul`, `#[derive(Mul(forward)]`, etc.) too.  Looks like I missed the most logical one to try.

Thanks, @JelteF.  That seems to have worked.
