### ISSUE TITLE
`derive(derive_more::From)` doesn't foward properly

### ISSUE THREAD

**Issue by CGMossa** [JelteF/derive_more#166]
My case is that I want something equivalent to this:
```rust
#[derive(Debug, Clone, Copy)]
pub struct ReplacementParameter(Probability);

impl From<ReplacementParameter> for f64 {
    fn from(value: ReplacementParameter) -> Self {
        value.0.into()
    }
}
```

Since `Probability` implements `TryFrom<f64>`. But `derive_more` is failing on that, even if I use `#[from(forward)]`.

What am I missing and maybe what is `derive_more` missing here?

**Comment by JelteF** [comment]
You're mixing From and TryFrom in this issue, which are different traits.

Can you share the a full code sample that you tried? (I don't see the
definition of Probability) What do you want to be able to do/what exact
implementation do you expect to be generated?

**Comment by JelteF** [comment]
Also what's the compile error that you are getting?

**Comment by tyranron** [comment]
@CGMossa forwarding is possible if `f64` implements `From<Probability>`. The current syntax on `master` and `1.0.0-beta.*` releases would be:
```rust
#[derive(Clone, Copy, Debug, Into)]
#[into(f64)]
pub struct ReplacementParameter(Probability);
```
However, if `f64` implements only `TryFrom<Probability>`, you should use `TryInto` instead, which, at the moment, doesn't support granular types, though (tracked by https://github.com/JelteF/derive_more/issues/98).

I'm closing this for now. Feel free to reopen or ping, if we haven't understood your use case and the desired feature correctly.

**Comment by CGMossa** [comment]
Err sorry for not following this or closing it. It has been too long since this, and I've recently recreated this example, without running into this hiccup.
