### ISSUE TITLE
TryInto with input type as error

### ISSUE THREAD

**Issue by Alxandr** [JelteF/derive_more#170]
I have code where I use `try_into` to match against another enum (generated by another macro), however I need the original input value in the case that the `try_into` failed. I think this is much more usefull than a `&'static str` in general, but at least it would be nice if this could be an option. So I'd get code like this:

```rust
#[derive(TryInto)]
enum Test {
  A(A),
  B(B),
}

impl TryFrom<A> for Test {
  type Error = Test;
  fn try_from(value: Test) -> Result<Self, Test> {
    match value {
      Test::A(a) => Ok(a),
      _ => Err(value),
    }
  }
}

.....
```

**Comment by JelteF** [comment]
Solved in 1.0.0-beta.6 we now return a dedicated error type: https://docs.rs/derive_more/1.0.0-beta.6/derive_more/struct.TryIntoError.html
