### ISSUE TITLE
Invalid syntax in Display fmt fails silently

### ISSUE THREAD

**Issue by krallin** [JelteF/derive_more#184]
Consider this code:

```rust
use derive_more::Display;

#[derive(Display)]
#[display(fmt = "Stuff({})", .bar)]
pub struct Foo {
    bar: String
}

fn main() {
    println!("{}", Foo { bar: "test".into() });
}
```

This prints just `test`. Similarly, if you do this, it still prints `test`: 

```rust
#[derive(Display)]
#[display(fmt = "Stuff({})", .barrrrrrr)]
pub struct Foo {
    bar: String
}
```

The correct syntax here would be to use just `bar` in the format, but that's not super obvious since no error is raised.

Perhaps this could be fixed to inform the user that the format is just wrong?

Thanks!

**Comment by tyranron** [comment]
cc @ilslv

**Comment by ilslv** [comment]
@tyranron should we add [`trybuild`](https://docs.rs/trybuild/1.0.56/trybuild/) to test invalid inputs?

**Comment by tyranron** [comment]
@ilslv seems reasonable.

**Comment by ilslv** [comment]
@tyranron ping
