### ISSUE TITLE
Complete enum derives with getters which return Option<&T>

### ISSUE THREAD

**Issue by MTCoster** [JelteF/derive_more#186]
*I'm submitting this as an issue to gather feedback; I'm happy to do the work on an implementation if this is a desired feature.*

---

Currently I can use a combination of `IsVariant` and `Unwrap` to build an `Option<T>` for a specific variant of an enum.

It would be nice to be able to derive a getter which combines this functionality. For instance:

```rust
#[derive(GetVariant)]
enum MyEnum<A, B> {
    VarA(A),
    VarB(B),
}
```

Becomes:

```rust
enum MyEnum<A, B> {
    VarA(A),
    VarB(B),
}

impl <A, B> MyEnum<A, B> {
    fn var_a(&self) -> Option<&A> {
        match self {
            Self::VarA(var_a) => Some(var_a),
            _ => None,
        }
    }

    fn var_b(&self) -> Option<&B> {
        match self {
            Self::VarB(var_b) => Some(var_b),
            _ => None,
        }
    }
}
```

This somewhat mimics the implementation of `.ok()` and `.err()` on std's `Result<T, E>`, but those return `Option<T>` rather than `Option<&T>`. In that instance, this distinction doesn't matter as first convert to a `Result<&T, &E>` with `.as_ref()`.

**Comment by JelteF** [comment]
This si now possible using `#[try_unwrap(ref)]`: https://docs.rs/derive_more/1.0.0-beta.6/derive_more/derive.TryUnwrap.html
