### ISSUE TITLE
Derive trait implementations for standard pointer types

### ISSUE THREAD

**Issue by Fryuni** [JelteF/derive_more#189]
New derive for traits that implements them for standard pointers to the trait (`&`, `&mut`, `Box`, `Rc` and `Arc`), for example:

```rs
#[derive(RefImpls)
trait Foo {
  fn bar(&self) -> String;
}
```

Would generate:
```rs
impl<'a, T: Foo + ?Sized> Foo for &'a T {
    fn bar(&self) -> String {
        T::bar(self)
    }
}

impl<'a, T: Foo + ?Sized> Foo for &'a mut T {
    fn bar(&self) -> String {
        T::bar(self)
    }
}

impl<T: Foo + ?Sized> Foo for Box<T> {
    fn bar(&self) -> String {
        T::bar(self)
    }
}

// Rc and Arc are the same as Box
```

This allows consumers of the module using the trait to opt into dynamic dispatch. 

[Example using Box on the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7810d79249ae9a2099966c20f1964ebe)

If more people think this is a good idea I'd love to send a PR with this

**Comment by JelteF** [comment]
I'm not sure I understand the usecase for this. Could you show an example of when you would use this?

**Comment by Fryuni** [comment]
The playground link has a minimal example with a comment on why it is useful, but here is one use case that I've seen IRL (simplified for brevity):

A crate that defines a Cache and provides some implementations. This crate is used in many places as it is a basic building block.
```rs
pub trait Cache<V> {
  fn get(&self, key: &str) -> Option<V>;
  fn set(&mut self, key: &str, value: V) -> Option<V>;
}

pub type InMemoryCache<V> = HashMap<String, V>;

impl<V> Cache<V> for InMemoryCache<V> { ... };

pub struct NoopCache;

impl<V> Cache<V> for NoopCache { ... };
```

Another crate that defined the API for interpreting a User-Agent.
```rs
#[derive(Default)]
pub struct UserAgent {
  // --- other fields ---
  is_desktop: bool,
};

pub trait UserAgentInterpreter {
  fn interpret(&self, user_agent: &str) -> UserAgent;
}

pub struct NoopInterpreter;

impl UserAgentInterpreter for NoopInterpreter { ... } // Always the default
```

And finally, one crate that implements a cached UserAgentInterpreter, to be used on pay-per-request APIs:
```rs
pub struct CachedInterpreter<C: Cache<UserAgent>, I: UserAgentInterpreter> {
  cache: C,
  interpreter: I,
}

impl<C: Cache<UserAgent>, I: UserAgentInterpreter> UserAgentInterpreter for CacheInterpreter { ... }
```

All is well, no problems so far, at least not on those crates themselves. But for a consumer of those crates, there is no way to use dynamic dispatch. If you have an application that can initialize one of many interpreters and cache based on a configuration how would you model it? It would force consumers to have an enum of all the possible values, what if those are on dynamically linked libraries?

This is not possible with those crates:
```rs
fn get_cache() -> Box<dyn Cache> {
  // Read some configurations and decide which cache to use
}

fn get_interpreter() -> Box<dyn UserAgentInterpreter> {
  // Read some configurations and decide which interpreter to use
}

fn main() {
  // Box<dyn Cache> does not implement Cache
  // and Box<dyn UserAgentInterpreter> does not implement UserAgentInterpreter
  let interpreter = CachedInterpreter::new(get_interpreter(), get_cache());
}
```

As a consumer of those crates, you cannot implement `impl<C: Cache + ?Sized> Cache for Box<C>` yourself because of coherence rules. It has to be implemented on the crates that define the trait.

The same for `Arc`, `Rc`, `&` and `&mut`. This is quite the manual task, but can be automated with a macro. I think this derive macro fits this crate quite well 😄

**Comment by Fryuni** [comment]
@JelteF WDYT?

**Comment by tyranron** [comment]
@Fryuni 

First, `#[derive(...)]` attribute cannto be place onto a `trait` definition (onto a `struct`/`enum`/`union` only) 🤷‍♂️

Second, it seems that the following single blanket impl will do the job better:
```rust
impl<Ptr: Deref> Foo for Ptr where Ptr::Target: Foo {
    fn bar(&self) -> String {
        (**self).bar()
    }
}
```
as will allow any custom pointers in addition to `Box`, `Arc`, etc

**Comment by Fryuni** [comment]
I've seen macros on traits (`async-trait`, for example) so I thought that derive macros would also be allowed there. Since it isn't then I guess it shouldn't be here as it wouldn't be a derive macro.

Implementing using `Deref` causes a conflict for every impl provided along with the trait ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=bba29b0c247bdd84aae424ec93812bcb)).

**Comment by tyranron** [comment]
@Fryuni 

> Implementing using `Deref` causes a conflict for every impl provided along with the trait ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=bba29b0c247bdd84aae424ec93812bcb)).

Yup, this won't work when we implement our trait for a foreign type due to the nasty forward compatibility rule.

But it works when we implement our/foreign trait for _our_ type, since we control its future: [playground][https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e18a32ccfe8f5e73f5f8902a81448e86).  
I believe the later case is closer to the situation you've described above (poking with foreign traits for our types).

**Comment by Fryuni** [comment]
That is interesting... I think I'll have both options then:
- Deref mode: compatibility with anything that derefs, but the crate cannot provide impl on foreign types
- StdLib mode: only those types, but allows impl on foreign types

Sounds like a fun project. Do you think this is worth a PR here even though it is not a derive macro?
Otherwise, we can close this issue and I'll do it as a new crate 😄

**Comment by tyranron** [comment]
@Fryuni I don't see a nice fit of this into `derive_more`. Go ahead with your own crate 🙃
