### ISSUE TITLE
Feature: feature based assignment attribute macros

### ISSUE THREAD

**Issue by Davoodeh** [JelteF/derive_more#194]
### Skip this
This is my first issue in Rust related content so sorry if I don't know where to propose this idea or if it's logical/philosophically aligned with the community's culture.

As I was experimenting with Rust `cfg` macro and databases, I saw a very niche usecase that produced a bit of boilerplate code. I was trying to conditionally define a type and a constant like below:
```rust
#[cfg(feature = "mysql")]
/// docstring
pub type Connection = diesel::MysqlConnection;
#[cfg(feature = "postgres")]
/// TYPO OPS
pub type Connection = diesel::PgConnection;
```

### Why

- Debugging `cfg` based assignments is hard.
- Typos happen.
- Copying docstring and other attributes is copying not idea.

### Example
Roughly, this is what I have in my mind as a general syntax for it:
```rust
#[match_cfg(
    condition => body,
    $(more condition body)*
)]
pub/let type/const [: type_if_needed];
```

#### Main idea about `type`s
```rust
#[match_cfg(
    feature = "mysql" => diesel::MysqlConnection,
    feature = "postgres" => diesel::PgConnection,
)]
/// The only docstring I will need for all features.
pub type Connection;
```

This idea can be extended to `const` and normal `let` variable assignments too:

#### Const example
```rust
#[match_cfg(
    feature = "mysql" => "mydb is mysql",
    feature = "postgres" => "mydb is mysql",
)]
/// The only docstring I will need for all features.
pub const Connection: &str;
```

#### `let` variable example
```rust
#[match_cfg(
    feature = "mysql" => "mydb is mysql",
    feature = "postgres" => "mydb is mysql",
)]
/// The only docstring I will need for all features.
pub let connection;
```
```rust
#[match_cfg(
    feature = "mysql" => "mydb is mysql",
    feature = "postgres" => "mydb is mysql",
)]
/// The only docstring I will need for all features.
pub let connection: &str;
```

#### Alternative way
This adds quite a bit of probably unnecessary complexity (I didn't personally try to implement these unlike others), but this would be nice too, to have an alternative shorthand syntax for types that are from a single crate:
```rust
#[match_cfg(
    feature = "mysql" => MysqlConnection,
    feature = "postgres" => PgConnection,
)]
/// The only docstring I will need for all features.
pub type Connection = diesel;
```
or something like:
```rust
#[match_cfg(diesel::{
    feature = "mysql" => MysqlConnection,
    feature = "postgres" => PgConnection,
})]
/// The only docstring I will need for all features.
pub type Connection;
```

### Why no pr (unimportant)
I just learned Rust and I'm unable to contribute to such established crate. Not to mention there is no exact "noob friendly" guide for new contributors or whatever (so if anybody reading this thinks they can help me get started with contributing please reply). So, I just thought I let people know what I think and leave.

Regardless, I implemented something like this as a proc_macro with a bit of difference. Also only supports features.

Here's the code if anybody wants to read it (noob alert): https://pastebin.com/WjtnYJV6

I will write what I want to support all of the examples (not the alternative syntax for now) and share here when done, but I doubt if anybody finds it useful in regards of helping to implement this feature.

**Comment by ilslv** [comment]
@Davoodeh I don't think, that this macro should be part of the crate, as it focuses on `#[derive]` macros. Though you are not the only one, who thinks, that `cfg` macro maybe hard to use sometimes and there already are existing macros similar to what you have described: [`cfg_match`](https://docs.rs/cfg-match/0.2.1/cfg_match/macro.cfg_match.html), [`cfg_if`](https://crates.io/crates/cfg-if)  , [`efg`](https://crates.io/crates/efg)

**Comment by Davoodeh** [comment]
Thank you for mentioning the crates.
I'm stilling getting the hang of finding crates. By my searches, nothing showed up.

Regardless, I keep this issue opened for further discussion until somebody closes it. However, since I have heard that in Rust mindset, every crate must be as minimal as possible, then I think your answer concludes this talk.

Thanks again.

**Comment by Davoodeh** [comment]
I just took a look at [cfg_match](https://docs.rs/cfg-match/0.2.1/cfg_match/macro.cfg_match.html) (or equally [cfg_if](https://docs.rs/cfg-if/1.0.0/cfg_if/)), [efg](https://docs.rs/efg/0.1.2/efg/) crates as ilslv kindly pointed to and I'd like to comment on them and how they differ (however not essentially much) with what I proposed.

`efg` is simply an alias for `any`, `all` and `not` operators in `cfg`. Meaning it really doesn't do anything at all, it's simply a syntatic sugar or something of that category.

`cfg-match` or for that matter `cfg-if` are closer to my vision but the issue remains with two of the main reasons I proposed my way of things. 

> - Typos happen.
> - Copying docstring and other attributes is copying not idea.


```rust
cfg_match! {
    feature = "foo" => {
        /// doc
        pub type connection = something;
    }
    _ => {
        /// doc
        pub type connection = else;
    }
}
```

If the code below would work with this package, it would remove the need for the macro I provided, but for whatever reason I couldn't get it to work:
```rust
// NOTE not the exact code
/// doc
pub type connection = cfg_match! {
    feature = "foo" => something,
    _ =>  else
};
// Yields error: "expected type but `cfg_match` doesn't return type" or something like this.
```

P.S: I think if the match_cfg generally avoids the documentation is better. It just adds a whole another level of complexity to the macro. Maybe it's wiser to split this in 2 macros, `match_cfg` and `match_doc` like below (also worth mentioning that I think it's a good idea to set two "IMPLICIT ARM"s for docs in both of the macros):
```rust
#[match_doc(
    feature = "mysql" => /// The docstirng
    feature = "postgres" => /// The docstring
    // THE IMPLICIT ARM which is assigned automatically regardless of the features for the documentation:
    // all(doc, not(any(feature = "sqlite", feature = "postgres" /* and more if it had more above */))) =>
    //     /// The docstring (of the first one? or idk take it from somewhere as the default docstring)
    //     ///
    //     /// NOTE that the real value will not be this, rather something
    //     /// definitive that is determined based on the compile type features.
    //     /// See the source for the actual possible values or compile the docs
    //     /// with one of \"sqlite\", \"mysql\", (or other features if given) features.
)]
#[match_cfg(
    feature = "mysql" => MysqlConnection,
    feature = "postgres" => PgConnection,
    // THE IMPLICIT ARM which is assigned automatically regardless of the features for the documentation:
    // all(doc, not(any(feature = "sqlite", feature = "postgres" /* and more if it had more above */))) => dyn Any,
)]
pub type Connection;
```
