### ISSUE TITLE
Is it possible to use Debug print `{:?}` to print when we have `Option::None` and Display `{}` when we have `Option::Some(T)` where T is guaranteed to implement Display? 

### ISSUE THREAD

**Issue by weezy20** [JelteF/derive_more#199]
Currently I have something like this : 
```rust
#[display(fmt = "VarDecl IDENTIFER : '{}', Expression : {:?}", name, initializer)]
 VarDecl {
        name: String,
        initializer: Option<Box<Expression>>,
},
 ```
Which prints the `Debug` print for both variants of `initializer` which is an option. I would however like to change that and use `{}` Display prints when I know I have a `Some` variant. Is it possible to achieve this ?

**Comment by ilslv** [comment]
@weezy20 I think it's out of scope of this crate, but what you are trying to do can be easily achieved with something like:


```rust
struct DisplayOption<T>(Option<T>);

impl<T: Display> Display for DisplayOption<T> { ... }

#[display(fmt = "VarDecl IDENTIFER : '{}', Expression : {}", name, "DisplayOption(initializer)")]
VarDecl {
    name: String,
    initializer: Option<Box<Expression>>,
},
```

**Comment by tyranron** [comment]
@weezy20 it's not possible out-of-the-box with [standard `format!` syntax](https://doc.rust-lang.org/stable/std/fmt/index.html), thus cannot be supported by `derive_more` out-of-the-box too, as it effectively expands into the code using `format!` syntax.

But, you may achieve this by providing a custom formatting wrapper, and using it when the formatting happens:
```rust
struct DebugOrDisplay<T: ?Sized>(pub T);

impl<T: fmt::Display> fmt::Display for DebugOrDisplay<Option<T>> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match &self.0 {
            Some(v) => write!(f, "{}", v),
            None => write!(f, "{:?}", &self.0),
        }
    }
}

#[display(fmt = "VarDecl IDENTIFER : '{}', Expression : {:?}", name, "DebugOrDisplay(initializer)")]
 VarDecl {
        name: String,
        initializer: Option<Box<Expression>>,
},
```
