### ISSUE TITLE
A derived trait providing access to the inner type of a newtype

### ISSUE THREAD

**Issue by fjarri** [JelteF/derive_more#201]
While derived `From` and `AsRef` already remove some boilerplate when defining newtypes, it would be convenient to have a more specialized "newtype" trait that would give access to the inner type. That is, `derive_more` would define
```rust
trait Newtype {
    type Inner;
}
```
And writing
```rust
#[derive(Newtype)]
struct Outer(SomeType);
```
would produce
```rust
impl Newtype for Outer {
    type Inner = SomeType;
}
```

The associated `Inner` may be bounded:
```rust
trait Newtype: Sized {
    type Inner: Into<Self>;
}
```
In which case `#[derive(Newtype)]` would also derive `From`.

Does that sound like something you'd want to add to the crate? I can make a PR.

**Comment by JelteF** [comment]
I'm don't really understand what this provides to the user. How would you use this new Newtype trait as a user?

**Comment by fjarri** [comment]
Oh man, it's been a year, I don't remember the context anymore. You can close it, I'll reopen if it comes up again.

**Comment by JelteF** [comment]
Yeah sorry for the late response
