### ISSUE TITLE
Warning about quasi quoting

### ISSUE THREAD

**Issue by vorner** [JelteF/derive_more#21]
When compiling the `derive_more` crate, I get a bunch of warnings like this:

```
warning: Quasi-quoting might make incremental compilation very inefficient: NtIdent(..)
   --> /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/derive_more-0.6.1/src/lib.rs:149:29
    |
149 |         #[proc_macro_derive($trait_)]
    |                             ^^^^^^^
...
161 | create_derive!(into, Into, into_derive);
    | ---------------------------------------- in this macro invocation
```

It happens on nightly with incremental compilation turned on (`CARGO_INCREMENTAL=1`). I'm not sure what exactly it means and how to mitigate it, but I think it should be looked into if this can be prevented somehow.

**Comment by JelteF** [comment]
I don't think this is the case anymore. Closing this.
