### ISSUE TITLE
Naming Library crate `core` prevents  project from compiling

### ISSUE THREAD

**Issue by tolumide-ng** [JelteF/derive_more#211]
Hello everyone, 
Great job on this project, and thank you so much.
I was not sure if I should drop this here, but I thought someone else might encounter this problem on their Rust `Library crate` in the future.

Naming your Library crate `core` could prevent your code from compiling with an error like this:
```
| #[derive(Debug, Display)]
                   ^^^^^^^ could not find `fmt` in `core`
```

All you need to do is to change your library's name on Cargo.toml.
In my case, I changed I did this

```
[package]
name = ~"core"~ "library new name"
version = "0.1.0"
edition = "2021"
```

**Comment by JelteF** [comment]
Yeah, the solution is simply not to do that and use different name. Calling your crate std is similarly not a great idea.
