### ISSUE TITLE
Consider using non string expressions

### ISSUE THREAD

**Issue by ModProg** [JelteF/derive_more#217]
This woud allow easier writing of expressions like:
```rs
#[display(fmt = "Focus {_0} {}", "if *_1 {\"global\"} else {\"\"}")]
struct Fullscreen(Edt, bool);
```
which becomes, also improving highlighting for types such as strings
```rs
#[display(fmt = "Focus {_0} {}", if *_1 {"global"} else {""})]
struct Fullscreen(Edt, bool);
```
Clap switched to this with their 4.0 release: https://docs.rs/clap/latest/clap/_derive/index.html

There is also a helper crate that could make parsing these easier: https://lib.rs/crates/attribute-derive (Disclaimer, I have written this crate).

**Comment by tyranron** [comment]
@ModProg thanks, we [do consider this](https://github.com/JelteF/derive_more/issues/202#issuecomment-1298349654) before going 1.0.

> There is also a helper crate that could make parsing these easier: https://lib.rs/crates/attribute-derive (Disclaimer, I have written this crate).

I have written a [similar crate](https://docs.rs/synthez/0.2.0/synthez/derive.ParseAttrs.html) 😅
However, I doubt this kind of things would be used by `derive_more` as we care about minimizing dependencies a lot here.

**Comment by ModProg** [comment]
Great to hear




> I have written a [similar crate](https://docs.rs/synthez/0.2.0/synthez/derive.ParseAttrs.html) 😅

Looks interesting, will definitely check it out.

**Comment by JelteF** [comment]
Idea sounds reasonable and indeed good 1.0 material. @tyranron @ilslv  I think it makes sense if one of you picks this up, given this applies mostly (or only) to the Display style derives,

**Comment by ilslv** [comment]
@JelteF @tyranron as we are introducing breaking changes to `Display`-like macros, I want to propose some changes to the API:

1. Remove `fmt =` prefix. I often forget to place it and get frustrated with compile-time errors. Also I don't see how it's useful in any way, because without it macro attribute is descriptive enough.
2. Change `bound = ...` to `bound(...)`.

---

Pre `1.0`:

```rust 
#[derive(Display)]
#[display(fmt = "{} {} {}", "a.my_function()", "b.to_string().len()", "c")]
#[display(bound = "T: MyTrait, U: Display, V: Display")]
struct MyStruct<T, U, V> {
    a: T,
    b: U,
    c: V,
}
```

After `1.0`:

```rust 
#[derive(Display)]
#[display("{} {} {}", a.my_function(), b.to_string().len(), c)]
#[display(bound(T: MyTrait, U: Display, V: Display))]
struct MyStruct<T, U, V> {
    a: T,
    b: U,
    c: V,
}
```

**Comment by ModProg** [comment]
I found another place that might be related:

```rs
// does not work
#[from(types(&str))]
// does work
#[from(types("&str"))]

**Comment by JelteF** [comment]
@ilslv sounds good

**Comment by ilslv** [comment]
@tyranron @JelteF I've encountered interesting tradeoff and would like to get your opinions on that. 

### Option 1

We could fairly parse `args` in `#[display("literal", args)]` with `syn::Punctuated<syn::Expr, syn::token::Comma>`, but this would require `syn`'s `full` feature and increase compilation times. 

### Option 2

We just parse everything that looks like `, ident,` and try to lookup that ident in fields. If successful, add it to the bounds. This may give us false positives with something like: `#[display("{}", no_bounds(field1, field2, field2))]`. `field2` here would definitely impose additional bounds.

### Option 3

Like option 2, but we will skip any nested groups like `(...)`, `[...]`, `{...}`, `<...>` and `|...|`. This would definitely decrease false-positives, but I think there may be still a sneaky way to bypass it.

### Option 4

Only infer bounds for fields explicitly defined in fmt string literal `"{field}"`. This is what `thiserr` does. This still could give us false-negatives like: `#[display("{field}", field = 123)]`.

### Option 5

Like option 4, but try to find every argument that starts with `literal =` and skip bounds for it. 

---

I think that it is very important to be conservative here and try to impose the least amount of false-positive bounds and push users to use `#[display(bound(...))]` for it. I would vote for something like options 3-5.

**Comment by ilslv** [comment]
Discussed with @tyranron:

We think it's possible to create perfect derive macro with option 3 and custom parsing. We should definitely check out [curated list of weirdest rust expressions™](https://github.com/rust-lang/rust/blob/master/src/test/ui/weird-exprs.rs) 🙃

**Comment by JelteF** [comment]
> but this would require syn's full feature and increase compilation times

Do we have any data on how much this would increase compilation time. It would be nice if we didn't have to implement a custom parser.

**Comment by tyranron** [comment]
@JelteF 

> It would be nice if we didn't have to implement a custom parser.

That wouldn't be something complicated. It should be much simpler than existing parser of formatting literal.
