### ISSUE TITLE
Rename CustomDebug

### ISSUE THREAD

**Issue by JelteF** [JelteF/derive_more#223]
Copied from #202 for a more structured discussion.

Written by @tyranron:

> 
> I would like in future to add more derives which overlap with the ones from `std`. For example, `#[derive(Clone)]` from `std` is very stupid when it comes to generics, because it's blindly pastes `: Clone` trait bound on types parameters rather than field types, thus leads to [tones of squatting](https://github.com/cucumber-rs/cucumber/blob/da1adca9724fa504f2f56d98ad63561bb779f940/src/writer/normalize.rs#L53-L62). We already have `CustomDebug` which overlaps with `#[derive(Debug)]` and cannot be named `Debug` because of implicit `prelude` import. 
> 
> Usually, we have a code style rule to sort any enumerations in alphabetical order, so the proposed naming change is to omit any possible moves in a list of derived traits when we go from `Debug` to `CustomDebug`, but rather to add a suffix in-place to the standard derive:
> - Instead of this:   
>    `#[derive(AsRef, Clone, Copy, Debug, Default, Display, Eq, Error, From, PartialEq)]` -> `#[derive(AsRef, CustomClone, CustomCopy, CustomDebug, CustomDefault, CustomEq, CustomPartialEq, Display, Error, From)]`
> - Have this:
>   `#[derive(AsRef, Clone, Copy, Debug, Display, Eq, Error, From, PartialEq)]` -> `#[derive(AsRef, CloneCustom, CopyCustom, DebugCustom, DefaultCustom, Display, EqCustom, Error, From, PartialEqCustom)]`
> 
> I would also consider some simpler/shorter suffix rather than `Custom`, but cannot invent any good candidate at the moment rather than `Smart` (which is not ideal, btw).
> 
> `#[derive(AsRef, CloneSmart, CopySmart, DebugSmart, DefaultSmart, Display, EqSmart, Error, From, PartialEqSmart)]`

Written by @JelteF 

> 
> Both proposed breaking changes sound good to me. Can you make separate issues for them so that they can be tracked in the 1.0.0 milestone? I see that 2 is already tracked in #217
> 
> Regarding suffix, one other idea that comes to mind is More (as in coming from derive_more). I don't have a strong preference to any of Custom, Smart or More (tbh all of them sound suboptimal, but I don't know a better one)
> 

Written by @tyranron 

> > Regarding suffix, one other idea that comes to mind is More (as in coming from derive_more). I don't have a strong preference to any of Custom, Smart or More (tbh all of them sound suboptimal, but I don't know a better one)
> 
> Nice idea. I do like it a lot ♥️
> 
> However, it seems that proc-macro shadowing [became allowed now](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cb2996dc27ebb499921f2ac494101abd), when we have an umbrella crate. So we can just use normal names for them:
> ```rust
> use derive_more::Debug;
> 
> #[derive(Debug)]
> struct MyStruct;
> ```
> 
> Still need to re-check this with tests.
>

**Comment by JelteF** [comment]
Would `derive_more::Debug` be a strict superset of the normal `Debug`? i.e. without specifying attributed it would do whatever the stdlib does? If so, it might make sense. If not, then I think users will often want to use `derive_more::Debug` derives and regular `Debug` derives in the same file. Then `derive_more::Debug` feels like a step back from `CustomDebug` even, since the again has the prefix and it's quite long to type:
```rust
use derive_more
#[derive(derive_more::Debug)]
struct MyStruct;

#[derive(Debug)]
struct MyStructNormal;
```

**Comment by tyranron** [comment]
@JelteF 

> Would `derive_more::Debug` be a strict superset of the normal `Debug`?

It depends on what we mean by a "superset" here. `std::Debug` is not clever when it comes to type parameters, as doesn't bound them structurally. This one:
```rust
#[derive(Debug)]
struct Foo<T>(PhantomData<T>);
```
will expand to:
```rust
impl<T: Debug> Debug for Foo<T> { ... }
```
while it's naturally expected to expand like (the behavior of `derive_more::Debug`) :
```rust
impl<T> Debug for Foo<T> where PhantomData<T>: Debug { ... }
```
Should we consider this more clever trait bounding as "superset"? 🤔

For any cases where `std::Debug` is clever enough, our macro would be as much clever. So, applying our macro instead of `std::Debug` only may make trait bounds more precise or meaningful.

> If not, then I think users will often want to use `derive_more::Debug` derives and regular `Debug` derives in the same file.

Makes sense, but I don't see this as that frequent situation that I'd want to avoid using `use derive_more::Debug as DebugClever` or `#[derive(derive_more::Debug)]`.

**Comment by ilslv** [comment]
For preserving history, written [here](https://github.com/JelteF/derive_more/pull/232#discussion_r1086704785)

> hmm... I'd say that the current `DebugCustom` implementation is not useful at all, in the contrast with `Display` and other `Display`-like derives. The problem is that it follows `Display`-like semantics, but in reality this is not what we expect. I'd propose to remake `DebugCustom` in a separate PR to follow its own `Debug` semantics inherited from std's `#[derive(Debug)]` with steroids in form of:
>
> structural bounding of type parameters (as we do for `Display`-like macros);
allowing to change how field is rendered granularly with `#[debug("fmt string", fmt, args)]` attribute;
fields ignoring with` #[debug(ignore)]`.
