### ISSUE TITLE
Full list of macros

### ISSUE THREAD

**Issue by andrewbaxter** [JelteF/derive_more#229]
I couldn't find anywhere in the docs with a full list of macros.  This would be very helpful as reference and probably make it clearer that `Add` doesn't derive "Add-like" features but rather _just_ add.

**Comment by andrewbaxter** [comment]
To be clear in case I'm coming at the documentation from a strange angle, https://jeltef.github.io/derive_more/derive_more/index.html appears to be just the readme.  There's a link on the side that says [See all derive_more's items](https://jeltef.github.io/derive_more/derive_more/all.html) but it shows nothing when I click on it.

There are links to specific traits.  Changing the trait name into another valid trait name gives a 404, so I don't think I just missed some links somewhere.

**Comment by JelteF** [comment]
We've recently changed how we generate docs, this will be addressed automatically once we release the next version. For now if you scroll down on the readme you can find the full (manually created) list there:
![image](https://user-images.githubusercontent.com/1162278/211936416-b4500a68-f91c-43c4-ab8c-b5af158025f8.png)

**Comment by andrewbaxter** [comment]
Oh awesome, okay! Thanks.
