### ISSUE TITLE
#[derive(Mul)] doesn't add anything but Mul

### ISSUE THREAD

**Issue by Susurrus** [JelteF/derive_more#23]
According to the README it should also implement `Div`, `Rem`, `Shr` and `Shl`. It doesn't seem to do this for any of my types. Additionally, it doesn't look like this is checked in the unit tests for this crate.

**Comment by JelteF** [comment]
You should add `#[derive(Div)]` if you want `Div`. It's just that the generated code for these traits is so similar to the `Mul` code that I don't show them all. Improvements to the docs for clarity are appreciated.

**Comment by JelteF** [comment]
All of these should just work if you do `#[derive(TraitName)]`, so in your case `#[derive(Rem)]`.

You can do all by doing `#[derive(Mul, Div, Rem, Shr, Shl)]`

**Comment by Susurrus** [comment]
Ahh, just looks like the README is really out of date then. Maybe I should change this issue to address updating the README to be correct?

**Comment by JelteF** [comment]
Yeah I tried to explain it like that, I'm just not great at writing docs. If you can make a PR to explain it clearer I'll gladly merge it.

**Comment by Susurrus** [comment]
I've got my hands in too many other cookie jars to help with a PR, sorry! Just wanted to bring it to your attention since I see this crate as being pretty useful!

**Comment by JelteF** [comment]
Closing this as I've made this behaviour explicit with the latest doc changes: https://github.com/JelteF/derive_more/blob/master/src/lib.rs#L55-L56

(This is not in the README or the rendered docs yet, will do that when I release)
