### ISSUE TITLE
Support inline variables in format strings in Display

### ISSUE THREAD

**Issue by WiSaGaN** [JelteF/derive_more#237]
Would be great to support the newly stabalized (1.67) format args
```rust
#[derive(Display)]
pub enum Foo {
    #[display(fmt="{_0}")]
    Bar(u32),
}
```
Currently it shows "cannot be formatted with the default parameter"

**Comment by ilslv** [comment]
@WiSaGaN this feature is already available on `main` https://github.com/JelteF/derive_more/pull/182 and will be included in the next release.

**Comment by WiSaGaN** [comment]
Didn't know that. Thanks!
