### ISSUE TITLE
`CHANGELOG.md` does not adhere completely to the Keep A Changelog format

### ISSUE THREAD

**Issue by LikeLakers2** [JelteF/derive_more#253]
Hi! I was looking through some crates on crates.io, and I happened to chance upon the `CHANGELOG.md` file within this repository.

I noticed that it didn't quite adhere properly to the Keep A Changelog format - despite claiming otherwise in its opening lines. For example:

* The header is `Change Log` instead of `Changelog` (pedantic, I know, but it's good to be consistent c: )
* The `1.0.0 - 2023-??-??` is clearly representative of an `Unreleased` section - so it should be labeled as such.
* The various sections under each version ("Breaking Changes", "New Features", "Improvements", "Fixes") do not match the "Types of changes" that Keep A Changelog proposes to use.

To be clear, I'm being pedantic with all this. The changelog is actually fine as-is! Importantly, it's kept consistent, so it's not as if it's hard to read.

But if you'd allow me, I'd gladly go through and rewrite (or rather, rearrange) `CHANGELOG.md` to fix the things listed above. Would that be okay?

**Comment by JelteF** [comment]
Sounds good to me. Seems like an easy to review PR (I love receiving those)

**Comment by LikeLakers2** [comment]
Okay! I'll start work on it sometime in the next couple days (currently working on my own projects and all).

**Comment by tyranron** [comment]
Fixed in #256
