### ISSUE TITLE
derive_more::Display quietly ignores enum variant fmt args

### ISSUE THREAD

**Issue by stepancheg** [JelteF/derive_more#258]
```
#[derive(derive_more::Display)]
enum FooBar {
    #[display(fmt = "hello {}", .0)]
    Baz(u32),
}

fn main() {
    println!("{}", FooBar::Baz(42));
}
```

Prints

```
42
```

should print

```
hello 42
```

Or at least fail.

Version 0.99.17.

**Comment by ilslv** [comment]
@stepancheg you should use `_0` instead of `.0`:

```rust
#[derive(derive_more::Display)]
enum FooBar {
    #[display(fmt = "hello {}", _0)]
    Baz(u32),
}

fn main() {
    println!("{}", FooBar::Baz(42));
}
```

On `main` we already have compile error test for this case. 

https://github.com/JelteF/derive_more/blob/70c43f919f39626179a4a53490248769fa240655/tests/compile_fail/display/unnamed_field_prefixed_with_dot.rs#L1-L3

**Comment by stepancheg** [comment]
> On main we already have compile error test for this case.

Thanks!
