### ISSUE TITLE
`#[derive_more::Error]` refers to `std::`

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [JelteF/derive_more#261]
I did two simple libraries here: https://github.com/StackOverflowExcept1on/derive-more-issue/
- [lib-derive-more](https://github.com/StackOverflowExcept1on/derive-more-issue/tree/master/lib-derive-more)
- [lib-snafu](https://github.com/StackOverflowExcept1on/derive-more-issue/tree/master/lib-snafu)

Why doesn't the library provide `impl core::error::Error for Error`?

```rust
#![no_std]

#[derive(Debug, Eq, PartialEq, derive_more::Display, derive_more::Error)]
pub enum Error {
    #[display(fmt = "Unable to write result")]
    WriteResult,
}

pub type Result<T, E = Error> = core::result::Result<T, E>;

pub fn foo(a: i32, b: i32) -> Result<i32> {
    a.checked_add(b).ok_or_else(|| Error::WriteResult)
}
```

```
error[E0433]: failed to resolve: could not find `std` in the list of imported crates
 --> src/lib.rs:3:54
  |
3 | #[derive(Debug, Eq, PartialEq, derive_more::Display, derive_more::Error)]
  |                                                      ^^^^^^^^^^^^^^^^^^ could not find `std` in the list of imported crates
```

**Comment by JelteF** [comment]
The Error trait is not yet in `core` on stable. Currently it is only in `std`. So if you are compiling for a no_std environment you currently cannot use Error. It seems there's an unstable feature though to enable Error in `core`, so maybe we should enable that when the std crate feature is not enabled: https://github.com/rust-lang/rust/issues/103765

**Comment by StackOverflowExcept1on** [comment]
Could you do an auto-detect using `#[cfg]`?

**Comment by StackOverflowExcept1on** [comment]
In the `snafu` crate, they did a trick with conditional compilation and `snafu::Error` that turned out to be compatible with `std::error::Error`
https://github.com/shepmaster/snafu/blob/main/src/lib.rs#L354

**Comment by tyranron** [comment]
Seems reasonable to have in under feature flag.

**Comment by JelteF** [comment]
@StackOverflowExcept1on I created a PR that adds support for the Error derive in no_std environments in #268. It also includes some tests, but could you double check that it solves your problem?

**Comment by StackOverflowExcept1on** [comment]
Looks good, but for example snafu has a polyfill for `core::error::Error` that can be used at stable rust in `no_std`.

**Comment by tyranron** [comment]
@StackOverflowExcept1on is having a polyfill critical for you? We don't want deviate much from what `std`/`core` have.

**Comment by StackOverflowExcept1on** [comment]
@tyranron this is not critical, but it would be useful for stable crates

**Comment by JelteF** [comment]
I looked into using the same polyfill approach as snafu. But I don't that fits well with the ideas behind this crate, especially since the Error trait is on the path to being stabilized (although that will probably take some more time). Every Error derive crate creating its own Error polyfill is also really bad for the general ecosystem, since none of them will be able to work together. It might be better to actually have add a crate feature which uses the snafu polyfill.

**Comment by StackOverflowExcept1on** [comment]
btw https://github.com/rust-lang/rust/pull/125951
