### ISSUE TITLE
Release a version of the crate that support no_std

### ISSUE THREAD

**Issue by tdelabro** [JelteF/derive_more#267]
hello,

I noticed that the current version of the crate, on `main`, does have a `std` feature, meaning it also probably support building with `#[no_std]`.
This is great but sadly it is not part of the last available release on crates.io `0.99.17`.
Because I want to release my project on crates.io, I can only depends on crates published there, not through github, which is sad because I want to use your great crate, but I need to be able to build in `no_std`.

Would you consider releasing a new version of this crate soon?

**Comment by JelteF** [comment]
The currently released version should work fine with `#[no_std]`, without specifying anything. A new release will take some more time, as there's a few more changes that we want to make for the next release (which will be 1.0.0).

**Comment by tdelabro** [comment]
Oh, my bad tho. I will try to use it as it is in my project
