### ISSUE TITLE
Inconsistencies when deriving traits

### ISSUE THREAD

**Issue by gnzlbg** [JelteF/derive_more#27]
Given

```rust
struct R64(f64);
```

`#[derive(Mul)]` expands to:

```rust
impl<__RhsT> ::std::ops::Mul<__RhsT> for R64
where
    f64: ::std::ops::Mul<__RhsT, Output = f64>,
{
    type Output = R64;
    fn mul(self, rhs: __RhsT) -> R64 {
        R64(self.0.mul(rhs))
    }
}
```

but `#[derive(Add)]` expands to:

```rust
impl ::std::ops::Add for R64 {
    type Output = R64;
    fn add(self, rhs: R64) -> R64 {
        R64(self.0.add(rhs.0))
    }
}
```

So this means that `R64` implements `Add` but not `Mul`...

**Comment by gnzlbg** [comment]
looking at the implementation, this crate is not reusing any code between Add and Mul derives...

**Comment by JelteF** [comment]
These inconsistencies are there on purpose and are [documented](https://jeltef.github.io/derive_more/derive_more/mul.html): 

>Deriving Mul is quite different from deriving Add. It is not used to multiply two structs together. Instead it will normally multipy a struct, which can have multiple fields, with a single primitive type (e.g. a u64). A new struct is then created with all the fields from the previous struct multiplied by this other value.
>
>A simple way of explaining the reasoning behind this difference between Add and Mul deriving, is looking at arithmetic on meters. One meter can be added to one meter, to get two meters. Also, one meter times two would be two meters, but one meter times one meter would be one square meter. As this second case clearly requires more knowledge about the meaning of the type in question deriving for this is not implemented.

**Comment by gnzlbg** [comment]
So, I can't derive `Mul` for my wrapper type?

**Comment by JelteF** [comment]
Well, you can. You can do `2.0 * R64(1.0) == R64(2.0)`, you just cannot do `R64(2.0) * R64(1.0) == R64(2.0)`

**Comment by gnzlbg** [comment]
I see, well thanks for the quick answers.
