### ISSUE TITLE
`#[derive(Error)]` doesn't work with `no-std`

### ISSUE THREAD

**Issue by KSXGitHub** [JelteF/derive_more#299]
## Code

```rust
#![no_std]
use derive_more::{Display, Error};

#[derive(Debug, Display, Error)]
#[display(fmt = "This is an error message")]
pub struct MyError;
```

Repo: https://github.com/KSXGitHub/bug-report-derive-more-error-no-std

## Expected behavior

It compiles without error

## Actual behavior

```text
error[E0433]: failed to resolve: could not find `std` in the list of imported crates
 --> src/lib.rs:4:26
  |
4 | #[derive(Debug, Display, Error)]
  |                          ^^^^^ could not find `std` in the list of imported crates
  |
  = note: this error originates in the derive macro `Error` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0433`.
error: could not compile `test-derive-error` (lib) due to previous error
```

**Comment by tyranron** [comment]
@KSXGitHub yes, because `error` module is only present in `std`, to have it in `core` a [nightly `feature(error_in_core)` is required](https://github.com/rust-lang/rust/issues/103765).

We're not going to support this unless it landed into `core` on stable Rust.

**Comment by JelteF** [comment]
To be clear you need to use the current beta release of derive_more together with `feature(error_in_core)` to have the Error derive working on no_std.
