### ISSUE TITLE
Nice Crate

### ISSUE THREAD

**Issue by porky11** [JelteF/derive_more#30]
But I cannot use it in my case, because I create vector-like types, where I store my data as arrays, which don't implement traits like `Add`, `Sub` etc. :(

**Comment by JelteF** [comment]
If you implement these traits on a newtype that wraps the vector you can then derive it for structs containing these types. Like so:

```
struct PorkyWrapper(Vec<i32>)

impl Add for PorkyWrapper {
// your code
}

#[derive(Add)]
struct SomethingWithPorkywrapper {
   porky: PorkyWrapper,
}
