### ISSUE TITLE
Add Display

### ISSUE THREAD

**Issue by spease** [JelteF/derive_more#32]
Probably also only makes sense for types with one field (at least for an auto-derive).

Thanks.

**Comment by glandium** [comment]
Note the enum-display-derive crate has `#[derive(Display)]`

**Comment by glandium** [comment]
except enum-display-derive doesn't handle generics.

**Comment by JelteF** [comment]
I'm actually working on getting this added for types with one field (not for enums).

**Comment by JelteF** [comment]
An implementation for Display is now on master. When I have some time to update the docs I will release it. Any feedback before that is appreciated.

**Comment by JelteF** [comment]
Going to close this because it's fixed on master and docs are on master as well
