### ISSUE TITLE
unwrap: generate ref and refmut function

### ISSUE THREAD

**Issue by wiiznokes** [JelteF/derive_more#323]
It seems to have already this features when i look  at the code:

```rust
let state = State::with_attr_params(
        input,
        trait_name,
        "unwrap".into(),
        AttrParams {
            enum_: vec!["ignore", "owned", "ref", "ref_mut"],
            variant: vec!["ignore", "owned", "ref", "ref_mut"],
            struct_: vec!["ignore"],
            field: vec!["ignore"],
        },
    )?;
```

But there is no documentation for them. Also, when i try to use them in my enum, ref and ref_mut trigger a rust std macro instead:

```
#[derive(Unwrap)]
#[unwrap(ref_mut)]
pub enum NodeType {
   ...
```

**Comment by wiiznokes** [comment]
Ok so with 1.0.0-beta.6, it works1.0.0-beta.6. I will keep that open because there is no doc for it, but feel free to close it

**Comment by tyranron** [comment]
@wiiznokes it's present in docs for 1.0.0-beta.6: https://docs.rs/derive_more/1.0.0-beta.6/derive_more/derive.Unwrap.html

**Comment by wiiznokes** [comment]
Yep. Not in the read me tho
