### ISSUE TITLE
Support `TryIntoRef`

### ISSUE THREAD

**Issue by siefkenj** [JelteF/derive_more#340]
I am wondering if this project would be open to adding implementations of `TryFrom<&T> for &Inner` traits. It might look like,
```rust
#[derive(derive_more::TryIntoRef)]
enum Foo {
   X(String),
   Y(String)
}

fn main() {
   let foo = Foo::X("hi".to_string());
   let x: &String = foo.try_into().unwrap();
}
```

If so, I should be able to make a PR.

**Comment by JelteF** [comment]
With 1.0.0-beta.6 this is already supported afaik: https://docs.rs/derive_more/1.0.0-beta.6/derive_more/derive.TryInto.html

**Comment by siefkenj** [comment]
That's great news. Thanks!
