### ISSUE TITLE
`IsVariant` should annotate the generated methods with `#[must_use]`?

### ISSUE THREAD

**Issue by TheLostLambda** [JelteF/derive_more#349]
I'm thinking about using `IsVariant` to replace a set of manual methods I'd previously implemented:
![image](https://github.com/JelteF/derive_more/assets/6251883/5ee01171-bcb2-4eb2-af97-7109e943eb45)

I was happy to see that the methods were already `const`, but they could still be made `#[must_use]`! The reason it's in my code is because I got a pedantic clippy lint about it, but since `bool`s don't implement `Drop` and exist only to be eventually used (these static methods have no "side effects"), I think it's safe and reasonable to add this annotation! As I understand, this is what the standard library does for `Result`.

I think this would, technically, be a breaking change, so it might be good to get into 1.0, but I'm happy to quickly whip up a PR if you think this is a worthwhile addition!

Just let me know and I can get to work!

**Comment by JelteF** [comment]
Yeah, sounds great. A PR is definitely appreciated for this.
