### ISSUE TITLE
Backport Update to Syn 2

### ISSUE THREAD

**Issue by bash** [JelteF/derive_more#368]
Hi 👋🏼 

I'm currently working on reducing duplicate dependencies in @janhohenheim's Bevy game template [Foxtrot](https://github.com/janhohenheim/foxtrot) ([relevant PR in Foxtrot](https://github.com/janhohenheim/foxtrot/pull/311)). His template is quite representative of the kinds of dependencies that you'll find in Bevy games.

A couple of the dependencies (bevy_xpbd_3d, leafwing-input-manager, ruzstd) depend on derive_more which in turn depends on Syn 1. Most other dependencies have already updated to Syn 2.

I have backported the Syn 1 to 2 update to derive_more v0.99.17 in my [fork](https://github.com/bash/derive_more/tree/backport-syn-update). Would you be interested in upstreaming my backport and releasing a new patch version?

**Comment by JelteF** [comment]
Yeah sounds great

**Comment by JelteF** [comment]
I created the release-0.99 branch for this: https://github.com/JelteF/derive_more/tree/release-0.99

**Comment by JelteF** [comment]
Okay, I decided I had time now (and maybe not tomorrow). So I did some changes myself to get CI working again (I didn't realize you had done similar changes on your branch). And now I cherry-picked your commit that did all the syn2 migration stuff. And I now published 0.99.18

Thanks a lot for spending time on this!

**Comment by janhohenheim** [comment]
Thanks for the backport :)
