### ISSUE TITLE
Typo / confusing wording in From docs

### ISSUE THREAD

**Issue by joshka** [JelteF/derive_more#375]
At https://jeltef.github.io/derive_more/derive_more/from.html,

> When deriving for a tuple struct with a single field (i.e. a newtype) like this:
>
> ```rust
> #[derive(From)]
> struct MyInt(i32);
>```
>
> Code like this will be generated:
> ```rust
> impl ::core::convert::From<(i32)> for MyInt {
>    fn from(original: (i32)) -> MyInt {
>        MyInt(original)
>    }
>}
>```

The extra parentheses around i32 are confusing although this means the exact same thing as without the parentheses, this implies a tuple which would be represented as `(i32,)` here. I'd suggest replacing this with the following for better clarity:

```rust
impl ::core::convert::From<i32> for MyInt {
    fn from(original: i32) -> MyInt {
        MyInt(original)
    }
}
```

Alternatively make a note about how (x) is not the same as (x,) here.

Note this also applies to other examples in the same doc.

**Comment by JelteF** [comment]
Sounds reasonable, could you create a PR for the docs?

**Comment by joshka** [comment]
Yep, sure. I'm a little confused about the branching strategy you're using. Which branch are these docs coming from?

**Comment by JelteF** [comment]
Just the master branch (but the current master branch has many changes)

**Comment by joshka** [comment]
Ok, the docs in master are different and don't have this info anymore.

**Comment by JelteF** [comment]
Okay closing this issue then.
