### ISSUE TITLE
Optional support for inline attributes

### ISSUE THREAD

**Issue by glandium** [JelteF/derive_more#38]
It would be useful in some cases to have some of the trait methods have the `#[inline]` attribute, or a variant of it, like `#[inline(never)]` or `#[inline(always)]`.

**Comment by JelteF** [comment]
Good point, mostly `#[inline(always)]` seems useful for the small implementationss.

**Comment by glandium** [comment]
FWIW, I needed `#[inline]` on `From::from` for enum, but I can understand that there are cases where that might not be wanted.

**Comment by JelteF** [comment]
Can I ask why you needed it? For performance reasons?

**Comment by glandium** [comment]
Yes, and because I was crossing crate boundaries, so the compiler won't inline without LTO.

**Comment by JelteF** [comment]
I'm assuming this wasn't for enums? Because those implementations can grow quite big easily. I think it's good to make it the default for the struct ones though.

**Comment by glandium** [comment]
It was for an enum. Those grow in large *numbers* but each stays rather small.

**Comment by JelteF** [comment]
Ah, I was confusing the From implementation with the Into one. The From
creates a lot of small implementations while the Into creates 1 big one. I
agree that it should have inline(always) then. If you want to make a PR,
feel free to do so. It should be quite simple.

**Comment by glandium** [comment]
What do you expect the version number will be with those changes? 0.8.1? 0.9?

**Comment by JelteF** [comment]
It will be 0.9.0 and I will release it later today.

**Comment by JelteF** [comment]
It's released as 0.9.0 including the other changes listed in the changelog: https://github.com/JelteF/derive_more/blob/master/CHANGELOG.md
