### ISSUE TITLE
Weirdness about #[derive(Into)]

### ISSUE THREAD

**Issue by glandium** [JelteF/derive_more#40]
When using `#[derive(Into)]`, I got an error saying `Only structs can derive a constructor`.

Looking at the code, I see it was copy/pasted from `constructor.rs` and still talks about `#[derive(Constructor)]`, and the error message is still that of `constructor.rs`. I'm not sure why Into is not supported for things other than structs...

And the other suprise I got reading the source is that `#[derive(Into)]` actually implements... `From`. Which is understandable in some way, since `From` implies `Into`, but then why doesn't it support the same things as `#[derive(From)]`?

**Comment by JelteF** [comment]
The reason Into is not supported for enums is documented here: https://jeltef.github.io/derive_more/derive_more/into.html#enums
