### ISSUE TITLE
Deriving Display on never gives a warning

### ISSUE THREAD

**Issue by ndmitchell** [JelteF/derive_more#400]
I have a type:

```
#[derive(Display)]
pub struct NoHash(!);
```

When I moved from derive_more 0.99.17 to 1.0.0 this went from not showing any warnings, to showing a warning about having dead code. I think this is because warnings are now turned on for generated derive_more code (which is great), but you might want to special case the never type in some way, or turn off dead_code because never produces it.

**Comment by tyranron** [comment]
@ndmitchell 

```rust
#[derive(std::Debug)]
pub struct NoHash(!);
```

also produces it.
