### ISSUE TITLE
`derive_more::Error` macro collides with local `Error` enum, whereas `thiserror` is fine.

### ISSUE THREAD

**Issue by U007D** [JelteF/derive_more#401]
Seeing if I can replace `thiserror` with `derive_more`:

```rust
use derive_more::{Display, Error};

#[derive(Debug, Display, Error)]
enum Error {
    SomeError,
    // ...
}
```
gives a compilation error (`Error` is defined twice), whereas `thiserror` has no problem with the same:

```rust
use thiserror::Error;

#[derive(Debug, Error)]
enum Error {
    SomeError,
    // ...
}
```
compiles fine.

**Comment by tyranron** [comment]
@U007D please, read the ["Re-exports" README section](https://docs.rs/derive_more/1.0.0/derive_more/#re-exports).

This is intentionally and unlikely will be changed. You have 3 ways to handle this:

1. Either import `derive_more::Error` with renaming:
    ```rust
    use derive_more::Error as StdError;
    ```

2. Or import macro only without `Error` trait:
    ```rust
    use derive_more::derive::Error;
    ```

3. Or just rename your `Error` enum.

See also:
- https://github.com/JelteF/derive_more/issues/259#issuecomment-1673361586
- https://github.com/JelteF/derive_more/pull/273
- https://github.com/JelteF/derive_more/issues/271#issuecomment-2290994021

**Comment by U007D** [comment]
I would advocate leaving this as a decision for the user, but you've clearly considered this and made a call.  Thank you for this information.
