### ISSUE TITLE
From for unit enum variants

### ISSUE THREAD

**Issue by spearman** [JelteF/derive_more#408]
It seems like in the change from version 0.99 to version 1.0 that unit enum variants no longer implement from unit () by default.

For example:

```
#[derive(From)]
enum Myenum {
  Null,
  Bool(bool),
  Num(i32),
  Text(String)
}
```
Only implements `From<bool>`, `From<i32>` and `From<String>`, whereas before it would also implement `From<()>`. I tried adding the `#[from]` attribute to the unit variant, but then it doesn't implement From for any of the other variants, so they also need to `#[from]` attribute so I end up with:
```
#[derive(From)]
enum Myenum {
  #[from] Null,
  #[from] Bool(bool),
  #[from] Num(i32),
  #[from] Text(String)
}
```
Is there a better way to do this?

**Comment by JelteF** [comment]
Yeah, this these derives for `()` were removed by default as the feature was considered pretty useless: https://github.com/JelteF/derive_more/issues/106

What did you use it for?

**Comment by JelteF** [comment]
Regarding the easiest to maintain solution: Depending on how many times you need this, it be just be the easiest to implement the `From` implementation for `()` yourself manually.

**Comment by sjunepark** [comment]
Manual implementation is not hard, but in my case, I wanted to achieve something like `Display`

```rust
#[derive(Display)]
#[display("{_variant}")]
enum Inner {
    Y,
    K,
    N,
    E,
}
```

I ended up implementing something like below.

```
impl<T: AsRef<str>> From<T> for Inner {
    fn from(value: T) -> Self {
        match value.as_ref() {
            "Y" => Y,
            "K" => K,
            "N" => N,
            "E" => E,
            _ => unreachable!(),
        }
    }
}
```

I'm not sure if allowing `From` to handle unit variants will be appropriate, but _at least an error_ would have been nice. (For example, if I try to derive an `AsRef` on a enum, it errors.)
Applying `From` when there are unit variants show no errors at all, in my case's `Inner` above.

**Comment by spearman** [comment]
> Yeah, this these derives for `()` were removed by default as the feature was considered pretty useless: #106
> 
> What did you use it for?

I looked at where I was using it and really the only advantage is that it's usually shorter to type `().into()` than to type out the full enum variant (and path to bring it into scope). On the other hand it's a bit less clear so I think I prefer giving the name of the enum. I've actually removed it from my code now so it's no longer an issue for me. You can close this if you want.

**Comment by JelteF** [comment]
@sjunepark You can use `FromStr` for the exact conversion you're describing.

@spearman thank you, then I'll close this issue.
