### ISSUE TITLE
broken links on cargo.io preview

### ISSUE THREAD

**Issue by juleskers** [JelteF/derive_more#49]
Hi, I came here from your [Crate-of-the-Week nomination](https://users.rust-lang.org/t/crate-of-the-week/2704/386?u=juleskers) (congrats, by the way!)

I looked at the preview blurb on crates.io, specifically the examples of [generated code](https://crates.io/crates/derive_more#user-content-generated-code), however, all the links there lead to a Github 404 page.
The same links in the Readme on github work correctly.

Details, for the `From` link
link on cargo.io: https://github.com/JelteF/derive_more/blob/master/from.html (broken)
link on github:    https://jeltef.github.io/derive_more/derive_more/from.html (working).

Could you please update the link targets on crates.io?

**Comment by JelteF** [comment]
I've fixed this in the latest release
