### ISSUE TITLE
FromStr fails if Result has been overriden in parent module

### ISSUE THREAD

**Issue by spease** [JelteF/derive_more#50]
Looks like line 28 of derive_more/src/from_str.rs is where the issue occurs.

I'd guess that the preferred solution is to use ::std::result::Result instead of just Result so that you refer absolutely to the intended std Result type for the trait.

**Comment by JelteF** [comment]
I just released 0.11.0 this should fix this problem.

**Comment by spease** [comment]
Thanks. I'm not very good about coming back to tickets once the issue is resolved, so I'll assume that it's the case and reopen it if the problem crops back up.
