### ISSUE TITLE
Implementing PartialEqVariants for enum variants

### ISSUE THREAD

**Issue by vldm** [JelteF/derive_more#51]
I am wondering is there a way to derive PartialEq<VariantType> for Enum ?
This could be useful for writing protocols, or some other stuff where each variant of enum is strictly unique.

Example of usage:

```
#[derive(VariantsEq)]
enum HeterogeneousValue {
String(String)
U64(u64)
}
```

will derive:
`impl PartialEq<String> for HeterogeneousValue;`
`impl PartialEq<U64> for HeterogeneousValue;`

**Comment by JelteF** [comment]
I think the easiest way to do this now is to derive From and PartialEq for  and do 
```rust
assert!(HeterogeneousValue::U64(123) == 123.into())
```

I'm closing this as I think that way is more explicit
