### ISSUE TITLE
#[derive(Mul)] does not derive an `impl Mul<Self>`

### ISSUE THREAD

**Issue by jamadazi** [JelteF/derive_more#54]
When deriving `Mul` or `Div`, they do not derive impls of the trait for when both the LHS and RHS are of the newtype:

```rust
#[macro_use]
extern crate derive_more;

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
#[derive(Add, Sub, Mul, Div)]
struct MyInt(i32);

// have to implement this manually, as it is missing from derive_more
// otherwise, `MyInt * MyInt` does not work
impl ::std::ops::Mul<MyInt> for MyInt {
    type Output = MyInt;
    fn mul(self, rhs: MyInt) -> MyInt {
        MyInt(::std::ops::Mul::mul(self.0, rhs.0))
    }
}

// however, `impl Add<MyInt> for MyInt` is not necessary, as it is derived correctly

fn main() {
    let a = MyInt(10);
    let b = MyInt(20);
    let c = a + b; // this works
    let d = a * b; // this does not work without the manual impl above
    let e = a * 10; // this works
    let f = b / a; // this does not work either
}

```

**Comment by JelteF** [comment]
This is on purpose, because the semantics of mul and add are very
different. You can read the reasoning here:
https://jeltef.github.io/derive_more/derive_more/mul.html

**Comment by jamadazi** [comment]
OK, I understand. My specific usecase was a simple wrapper where I expected multiplication to just work normally, so I was surprised that it did not. I understand the reasoning now. A lot of use cases for newtypes require different semantics.

Closing this issue.
