### ISSUE TITLE
Why are Add and Mul handled differently?

### ISSUE THREAD

**Issue by adiba** [JelteF/derive_more#57]
In the macro expansion I see ` __RhsT` for as type parameter in `impl`-blocks for `Mul`, `Div`, `Rem` etc.
However, `Add` and `Sub` implementations for instance don't have these.

**Comment by JelteF** [comment]
It's explained in the first section here: https://jeltef.github.io/derive_more/derive_more/mul.html

**Comment by JelteF** [comment]
On master this is now possible by deriving `MulSelf` instead of `Mul`.

**Comment by JelteF** [comment]
This is now released as version 0.99.0. Announcement link: https://reddit.com/r/rust/comments/duptc0/derive_more_0990_released_biggest_release_ever
