### ISSUE TITLE
Add no-std support

### ISSUE THREAD

**Issue by gbip** [JelteF/derive_more#58]
Would it be possible to add `no-std` support for this crate ?

I am willing to implement it if it is not too complicated... :smile:

**Comment by JelteF** [comment]
Afaik it shouldn't be very complicated. I think all that's needed is
outputting implementations of core versions of all the traits instead of
the std ones when the nostd feature is enabled. Feel free to make a PR with
the necessary changes.

**Comment by gbip** [comment]
It seems that your are using a `HashMap` in [from.rs](https://github.com/JelteF/derive_more/blob/master/src/from.rs#L75) and there is no equivalent in `[no-std]`. Is this a blocking problem ?

**Comment by JelteF** [comment]
I would assume the no-std would apply to the generated code only, not the code I use to generate it. AFAIK the Hashmap is only used to generate the code.

**Comment by gbip** [comment]
Do you agree that what I should do is replace all the reference to std in the generated implementation (such as [here](https://github.com/JelteF/derive_more/blob/master/src/add_assign_like.rs#L28)) to references to either `core` or `std` based on the presence of the `no_std` feature ?

If I'm right then I thought about two solutions :
1.Wrap the call to `quote!` in a [cfg_if](https://docs.rs/cfg-if/0.1.6/cfg_if/) block everywhere but this will lead to duplicated code...
2. Create a macro that would wrap `quote!` and either spit out a `std` or `no_std` implementation.

Is the last solution a good way to solve this problem ?

**Comment by JelteF** [comment]
I think that should be enough to make it work with no_std indeed.
Regarding the way to solve it, I think it's best to make the std/core part of the quote a variable that you define outside the full quote and then reference it inside the full quote (possibly in the root of the package). So something like this:

```
let import_root = if std {
     quote!(::std)
} else {
    quote!(::core)
} 
    quote!(
        impl#impl_generics #import_root::ops::#trait_ident for #input_type#ty_generics #where_clause {
            #[inline]
            fn #method_ident(&mut self, rhs: #input_type#ty_generics) {
                #(#exprs;
                  )*
            }
        }
)
```

**Comment by gbip** [comment]
Do you have any idea about writing integration tests for this feature ?
Ideally we would run the test suite without the `no_std` feature and then with it but it does not seems possible at the moment...

**Comment by JelteF** [comment]
The failure crate does it apparently:
https://github.com/rust-lang-nursery/failure/issues/30
