### ISSUE TITLE
Implement FromStr for Enum

### ISSUE THREAD

**Issue by svenstaro** [JelteF/derive_more#59]
I have an enum with a long list like this:

```rust
enum ThingType {
    A,
    B,
    ...
    Z,
}
```

I want to be able to do

```rust
ThingType::from_str("A")
```
and get `ThingType::A`.

**Comment by JelteF** [comment]
That's a reasonable use case indeed. Feel free to send a PR that adds it.

**Comment by Razican** [comment]
It would be nice to also have the option to rename all to lowercase, camelcase and more, like [serde][serde].

[serde]: https://serde.rs/container-attrs.html#rename_all

**Comment by Luro02** [comment]
> It would be nice to also have the option to rename all to lowercase, camelcase and more, like serde.

You might be interested in [`strum`](https://crates.io/crates/strum), where the [`Display`](https://github.com/Peternator7/strum/wiki/Derive-Display) and [`EnumString`](https://github.com/Peternator7/strum/wiki/Derive-EnumString) derive macros are what you want:

```rust
use std::str::FromStr;
use strum::{Display, EnumString};

#[derive(Display, EnumString)]
#[strum(serialize_all = "SCREAMING-KEBAB-CASE")]
enum MediaType {
    Audio,
    Video,
    Subtitles,
    ClosedCaptions,
}

fn main() {
    assert_eq!(format!(MediaType::ClosedCaptions), "CLOSED-CAPTIONS".to_string());
    assert_eq!(MediaType::from_str("CLOSED-CAPTIONS"), MediaType::ClosedCaptions);
}
```
