### ISSUE TITLE
Implement Mul<Self> (and group?) on newtypes where inner: Mul<Self>

### ISSUE THREAD

**Issue by AGausmann** [JelteF/derive_more#64]
For example, a newtype struct around `i64`:

```
use derive_more::Mul;

#[derive(Mul)]
struct Int(i64);
```

The generic `impl Mul<__RhsT> for Int where i64: Mul<__RhsT>` does not satisfy `Int: Mul<Int>`. I believe that in any case where the inner value of a newtype can be self-multiplied, it makes sense logically that the newtype should also. 

I can implement it trivially, but just like most users of derive_more, I like getting rid of boilerplate:

```
impl Mul for Int {
    type Output = Int;

    fn mul(self, rhs: Int) -> Int {
        Int(self.0 * rhs.0)
    }
}

impl MulAssign for Int {
    fn mul_assign(&mut self, rhs: Int) {
        self.0 *= rhs.0
    }
}

**Comment by AGausmann** [comment]
Found duplicate #54, sorry about that. I do think there is a reasonable justification for adding this though.

**Comment by JelteF** [comment]
I think it makes sense to implement this as a separate derive with the name `MulSelf`, but only for newtypes, not types with multiple fields.

**Comment by AGausmann** [comment]
That sounds reasonable; that would make it more explicitly opt-in and would also prevent a breaking change for users who manually implement `Mul<Self>`

**Comment by JelteF** [comment]
It's on master now. Even for non newtypes and enums, because I could simply reuse the code for Add implementations.
