### ISSUE TITLE
derive custom Debug

### ISSUE THREAD

**Issue by mwillsey** [JelteF/derive_more#68]
Hello,

I enjoying using this crate to derive simple `Display` implementations, and it'd be swell if I could do the same for `Debug`.

Example use case, consider the classic `Point`:

```rust
#[derive(Display)]
#[display(fmt = "({}, {})", x, y)]
struct Point {
    x: i32,
    y: i32,
}
```

Frequently, I'll have a collection of `Point`s, and I want to debug that. I'm not going to derive `Display` on the collection, so I use `Debug`. However, for a structure as simple as `Point`, I'd rather always use the nicer format of `Display` (not the verbose derived `Debug`).

Thanks!

**Comment by JelteF** [comment]
Pushed this feature to master. You can do this by doing:
```rust
#[derive(DebugCustom)]
#[debug(fmt = "({}, {})", x, y)]
struct Point {
    x: i32,
    y: i32,
}
```

**Comment by adwhit** [comment]
Just wanted to not that I use this feature a lot (so thanks!) but I can't find it documented anywhere apart from this ticket. I often end up back here to remind myself how to do it - worth adding to docs somewhere?

**Comment by detly** [comment]
I was looking for this exact thing last week and almost missed it! See #172.
