### ISSUE TITLE
Better support for generics in Display

### ISSUE THREAD

**Issue by tyranron** [JelteF/derive_more#72]
## Current behavior

```rust
use derive_more::Display;

#[derive(Display)]
enum MyError<E> {
    #[display(fmt = "Custom error: {}", _0)]
    Custom(E),
    #[display(fmt = "{}", _0)]
    Concrete(DbError),
}

#[derive(Display)]
#[display(fmt = "database error")]
struct DbError;
```

```
   |
48 |     #[display(fmt = "Custom error: {}", _0)]
   |                                         ^^ `E` cannot be formatted with the default formatter
   |
   = help: the trait `std::fmt::Display` is not implemented for `E`
   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
   = help: consider adding a `where E: std::fmt::Display` bound
   = note: required because of the requirements on the impl of `std::fmt::Display` for `&E`
   = note: required by `std::fmt::Display::fmt`
```

With `enum MyError<E: std::fmt::Display> {` works fine.

## Desired behavior

As std `#[derive(Debug)]` does: imply `std::fmt::Display` bound on `impl` not the type.

```rust
#[derive(Debug)]
enum MyError<E> {
    Custom(E),
    Concrete(DbError),
}

#[derive(Debug)]
struct DbError;
```

[Compiles OK](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=19260ad4a9cae15099966d6b26331d78).

## Motivation

Traits bounds on the type itself pollute all the places where the type is used with these bounds (requires to specify them anywhere), which makes things quite unorthogonal. Its better to have trait bounds on `impl`s, so that user may decide whenever he wants these behavior or not in generic code by himself, rather than pushing him to apply this traid bound everywhere on type parameters.

**Comment by tyranron** [comment]
If there is no ideological issues with that, I can try to impl that by myself. The change seems to be backwards compatible.

**Comment by JelteF** [comment]
I understand your problem and I agree that it's not perfect. But the problem I see with your solution is that in the `#[display]` tag doesn't always require the the item to be Display, e.g.:
```rust
#[derive(Display)]
enum MyError<E> {
    #[display(fmt = "Custom error")]
    Custom(E),
    #[display(fmt = "{}", _0)]
    Concrete(DbError),
}
```
In that case I wouldn't want to put any bounds on E for the implementation of Display for MyError. So adding it there is not a full proof solution either.

**Comment by tyranron** [comment]
@JelteF true. I'm not familiar with proc macroses though... could this fact be figured out when parsing `#[display(...)]` attribute? If yes, we can imply bound only if type parameter is used there.

**Comment by JelteF** [comment]
We could check if the variable is used, but without parsing the fmt string ourselves we still wouldn't know if it requires display. e.g this would require Debug on E instead:
```rust
#[derive(Display)]
enum MyError<E> {
    #[display(fmt = "Custom error: {:?}", _0)]
    Custom(E),
    #[display(fmt = "{}", _0)]
    Concrete(DbError),
}
```

**Comment by tyranron** [comment]
@tyranron so, the question is "to parse or not to parse"? 🙃

As for me, checking whether variable is used is already smart enough. However, ideally the parsing should be involved.
