### ISSUE TITLE
derive Display for structs containing builtin types

### ISSUE THREAD

**Issue by segeljakt** [JelteF/derive_more#75]
I'm trying to use derive_more to derive Display for structs that contain types defined in the standard library, like `Option` and `Vec`, for example:

```rust
#[derive(Debug, Display)]
#[display(fmt = "|{}| {}", params, body)]
pub struct Lambda<'i> {
    pub params: Vec<Param<'i>>,
    pub body: Box<Expr<'i>>,
}
```

However, it does not appear to work, I'm getting this error:

```
[rustc] `std::vec::Vec<parse_tree::Param<'_>>` doesn't implement `std::fmt::Display`

`std::vec::Vec<parse_tree::Param<'_>>` cannot be formatted with the default formatter

help: the trait `std::fmt::Display` is not implemented for `std::vec::Vec<parse_tree::Param<'_>>`
note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
note: required because of the requirements on the impl of `std::fmt::Display` for `&std::vec::Vec<parse_tree::Param<'_>>`
note: required by `std::fmt::Display::fmt`
```

How do I get around this error?

**Comment by tyranron** [comment]
@segeljakt this error has nothing about this crate/macro.

As compiler points out:
```
help: the trait `std::fmt::Display` is not implemented for `std::vec::Vec<parse_tree::Param<'_>>`
```
`Vec` has [no implementation](https://doc.rust-lang.org/std/vec/struct.Vec.html#implementations) for `Display`. So, you cannot use `Vec` for `{}` placeholders.

Either use `{:?}` (`Vec` impls `Debug`) to render your vector, or use custom wrapper-type and provide a `Display` implementation for it.

**Comment by JelteF** [comment]
Closing this since this is no bug.
