### ISSUE TITLE
derive CheckedSub, CheckedAdd, etc.

### ISSUE THREAD

**Issue by Kylebrown9** [JelteF/derive_more#77]
I have a situation where it would be very useful to derive checked subtraction for a struct, because I fully expect underflow to occur.

The num-traits crate has a CheckedSub interface, and macros that implement it for the std number types. My proposal is to add a macro to derive_more that is capable of implementing CheckedSub, and other checked arithmetic, on structs whose members all implement CheckedSub.

https://github.com/rust-num/num-traits/blob/master/src/ops/checked.rs

**Comment by JelteF** [comment]
Cool idea, but I think it might make more sense to put these derives in the rust-num crate. This crate is mostly meant to derive standard library traits. Feel free to use the code in this crate as an example though, that might help a lot.
