### ISSUE TITLE
Conditionally compile features

### ISSUE THREAD

**Issue by SOF3** [JelteF/derive_more#81]
As this crate continues to expand, compilation time increases, but for a lot of cases, I simply don't want most of the macros available. (Although a release build of the current master only took 17.88 seconds on my CPU, and the derives aren't linked into the final executable anyway)

This issue suggests adding a feature for each derive macro.

**Comment by JelteF** [comment]
Sounds like a great idea a PR for that is welcome.

**Comment by WiSaGaN** [comment]
Consider this scenario, the final app depends on two library crates, which both depends on `derive_more`. The first library crates depends on full featured `derive_more`, while the second depends on just one feature. Does it make sense to just have the second to depend on full featured `derive_more` to only compile one copy for the app, thus reducing compile time?

**Comment by JelteF** [comment]
Nope, there's no reason to do what you're describing. There will always only be compiled a single copy of `derive_more`. If multiple dependencies, depend on different features, these features are merged together.

Source: https://stackoverflow.com/questions/45287134/how-can-i-prevent-cargo-from-merging-the-same-dependency-with-different-features
