### ISSUE TITLE
Is it possible to use one field to specify a derive?

### ISSUE THREAD

**Issue by alok** [JelteF/derive_more#86]
I have this struct:

```rust
Struct S {
	name: String,
	data: Vec<String>,
}
```

I want to derive `Iterator` on it by forwarding to `data`. Is there a way to specify that to generate the obvious derivation?

**Comment by JelteF** [comment]
At the moment not

**Comment by JelteF** [comment]
I just made a change to support this on the master branch for the Iterator derive. I'll modify most other traits to support the same.
