### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by nox** [JelteF/derive_more#91]
It would be nice of you to release a new version so that downstream users can gradually get rid of syn 0.15 in their crate graph.

**Comment by JelteF** [comment]
I've spent today implementing the last features I wanted to have in the next release. I'll spend some time coming week(s) to update the docs with all the new features that were added this release cycle. After that I'll publish a new release. I expect this will be around the end of this month.

**Comment by nox** [comment]
Cool, thanks for the heads-up!

**Comment by Robbepop** [comment]
Any updates on this? :)

**Comment by JelteF** [comment]
Probably somewhere in the coming week.

**Comment by JelteF** [comment]
Version 0.99.0 is now released. Announcement link: https://www.reddit.com/r/rust/comments/duptc0/derive_more_0990_released_biggest_release_ever/
