### ISSUE TITLE
Some test files are not distributed on crates.io

### ISSUE THREAD

**Issue by silwol** [JelteF/derive_more#94]
I packaged derive_more for Debian, and there a bug was reported that some of the tests have an entry in the `Cargo.toml` file, but didn't get distributed through crates.io which is our upstream source for the Debian packages. Would be great if you could check that all required get distributed with the next update. Thanks a lot.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933522

**Comment by JelteF** [comment]
Pushed a change that should resolve this next release. Is it common that tests are included in published packages?

**Comment by silwol** [comment]
I wouldn't know a significant reason to exclude them. During our packaging work we stumbled over several crates that do so, and it causes problems for us because the crates get built and tested before being uploaded to the Debian archive in order to ensure they can be used properly with the rustc version and the other crates we have available in the archive.
Thanks a lot for the fix.

**Comment by JelteF** [comment]
This is now released as version 0.99.0. Announcement link: https://reddit.com/r/rust/comments/duptc0/derive_more_0990_released_biggest_release_ever

**Comment by silwol** [comment]
Thanks for the change. Unfortunately, it seems the files didn't get published. I don't know the reason, because to me the glob pattern you added to `Cargo.toml` looks good.

**Comment by cuviper** [comment]
`"test/**/*.rs"` should be `tests/`, plural -- #117.

**Comment by silwol** [comment]
Thanks a lot @cuviper, didn't spot that.
