### ISSUE TITLE
Confusing `derive(From)` compilation error.

### ISSUE THREAD

**Issue by nathan-at-least** [JelteF/derive_more#96]
I am confused by a compilation error for `derive(From)`:

```bash
error[E0119]: conflicting implementations of trait `std::convert::From<std::io::Error>` for type `Error`:
 --> src/main.rs:7:17
  |
7 | #[derive(Debug, derive_more::From)]
  |                 ^^^^^^^^^^^^^^^^^
  |                 |
  |                 first implementation here
  |                 conflicting implementation for `Error`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0119`.
```

My type's definition is:

```rust
#[derive(Debug, derive_more::From)]
enum Error {
    Io(std::io::Error),
    Tokio(tokio::io::Error),
}
```

My projects' dependencies are:

```toml
[dependencies]
derive_more = "0.13.0"
tokio = { version = "=0.2.0-alpha.6", features = ["process"] }
```

My toolchain versions:

```bash
$ cargo --version ; rustc --version
cargo 1.40.0-nightly (3a9abe3f0 2019-10-15)
rustc 1.40.0-nightly (7979016af 2019-10-20)
```

**Discussion:**

The error message leads me to believe there are identical/ambiguous types in an enum, so that `derive(From)` cannot distinguish between them. Yet I believe `std::io::Error` and `tokio::io::Error` are distinct types. Here are the docs for [`tokio::io::Error` at v0.2.0-alpha.6](https://docs.rs/tokio/0.2.0-alpha.6/tokio/io/struct.Error.html).

Where does my confusion lie? Either something is wrong about my understanding or there is a bug in `derive(From)`.

You can browse the project in question at the appropriate revision: [`iomux` @ 8e65ea81](https://github.com/nathan-at-least/iomux/tree/8e65ea810cfec9ed8a53030ea098349abbbef8e9)

**Edit:** Added the type definition here to make this ticket clearer for newcomers.
**Edit:** Added toolchain versions.

**Comment by JelteF** [comment]
Please share the type definition. Otherwise it's impossible to give the reason for this error. Also, you haven't posted the error output for the second implementation of From. Are you sure you have not implemented one yourself as well?

**Comment by nathan-at-least** [comment]
Apologies for missing the type definition. It's here:

```rust
#[derive(Debug, derive_more::From)]
enum Error {
    Io(std::io::Error),
    Tokio(tokio::io::Error),
}
```

There is no other error output! That's why I'm confused. I'm not aware of any other `From` implementation on my own `Error` struct. I wondered if I was getting confused by the name `Error` (and maybe compilation message was about a different identifier), so I renamed `struct Error` to `struct MyError`, and rustc indeed complains about `MyError`.

**Comment by JelteF** [comment]
That should definitely work (assuming the tokio Error is not a type alias
of the std). Two things that you can try:
- try latest master of derive_more
- check the output of the derive using "cargo expand", copy paste it in
your source file, remove the derive, compile. That way you get much clearer
errors. https://github.com/dtolnay/cargo-expand

**Comment by nathan-at-least** [comment]
Ah, it looks like `tokio::io::Error` is a type alias: https://github.com/tokio-rs/tokio/blob/master/tokio/src/io/mod.rs#L64

Apologies for the confusion.

Would it be possible for `derive(From)` to somehow detect type aliases and improve the error message?

**Comment by JelteF** [comment]
That definitely explains it. And no it's not possible to give better errors in this case, because macro expansion doesn't have any type information (only AST info).
